import LegalPage from "../../components/legal/LegalPage";

const canonical = "https://www.storvex.rw/terms";

export const metadata = {
  title: "Terms of Service — Storvex",
  description: "The terms that apply when businesses and users access Storvex.",
  alternates: { canonical },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <LegalPage eyebrow="Legal" title="Terms of Service" intro="These terms govern access to and use of Storvex. Storvex is a product operated by RURAXIS.">
      <section><h2>1. The service</h2><p>Storvex provides tools for businesses to manage activities such as inventory, sales, expenses, cash, workers, customers, suppliers, branches, reporting, Marketplace listings, and optional communications and AI-powered workflows. Features may vary by account, plan, configuration, location, provider availability, or stage of release.</p></section>
      <section><h2>2. Business accounts and authorised users</h2><p>A person creating or administering an account for a business confirms that they are authorised to act for that business. The business is responsible for its account, its authorised users, the accuracy of information it provides, and keeping credentials secure. Users must provide accurate account information and promptly tell us at <a href="mailto:support@storvex.rw">support@storvex.rw</a> if they suspect unauthorised access.</p></section>
      <section><h2>3. Business and customer data</h2><p>The business retains responsibility for the data it and its users enter, upload, publish, or connect to Storvex. The business must have the rights and permissions needed to use that data and must give required notices to customers, workers, suppliers, message recipients, and other people. The business authorises RURAXIS and its service providers to process that data as needed to provide and protect Storvex and follow the business’s instructions.</p></section>
      <section><h2>4. Marketplace</h2><p>Storvex may let businesses publish stores and product listings for visitors to discover and contact them. The listing business is responsible for its products, prices, descriptions, availability, fulfilment, customer service, and compliance with applicable requirements.</p><p className="legal-note"><strong>Marketplace payments are not processed through Storvex.</strong> Any purchase, payment, delivery, return, or other transaction is arranged directly between the visitor and the listing business. Storvex is not the seller, buyer, payment processor, or a party to that transaction.</p></section>
      <section><h2>5. WhatsApp and other communications</h2><p>WhatsApp features are optional and depend on Meta’s services and approval. A business that enables them must comply with applicable law and the current WhatsApp and Meta terms, messaging rules, template requirements, and consent or opt-in requirements. The business is responsible for the recipients it selects and the content and timing of its messages. Third-party charges or restrictions may apply.</p></section>
      <section><h2>6. Plans and access</h2><p>Some features may be available only on particular plans or during a trial. Current plan descriptions presented in Storvex or on our pricing page form part of the service information available when a business chooses a plan. We may change plans or feature availability and will provide notice where reasonably appropriate. These terms do not create any refund, renewal, or fixed-price commitment not separately presented and agreed during purchase.</p></section>
      <section><h2>7. Acceptable use</h2><p>Users must not use Storvex to break the law or another person’s rights; send unlawful, deceptive, abusive, or unsolicited communications; upload malicious code; probe or bypass security; interfere with the service; access another account without permission; scrape the service in a way that harms it; or use Storvex to create or distribute harmful or fraudulent material.</p></section>
      <section><h2>8. Third-party services</h2><p>Storvex may connect with services provided by Meta, Twilio, Resend, OpenAI, and other infrastructure or business-service providers. Those services may be governed by separate terms and privacy practices. We do not control their independent services, decisions, availability, or changes.</p></section>
      <section><h2>9. Intellectual property</h2><p>RURAXIS and its licensors retain rights in Storvex, including its software, design, branding, and documentation. These terms give authorised users a limited, non-exclusive, non-transferable right to use the service for the business’s internal operations while the account is permitted to access it. Businesses retain rights in their content and grant us the limited rights needed to host, process, display, and transmit it to provide the service.</p></section>
      <section><h2>10. Suspension and termination</h2><p>We may limit or suspend access where reasonably necessary to address security risk, unlawful or harmful activity, material breach of these terms, non-payment where payment is required, provider restrictions, or risk to Storvex or others. Where practical, we will seek to give notice and an opportunity to address the issue. A business may stop using Storvex and may request account or data deletion subject to legitimate retention needs.</p></section>
      <section><h2>11. Service changes and availability</h2><p>We work to keep Storvex useful and available, but the service may sometimes be interrupted, changed, or discontinued. We do not promise uninterrupted operation or that every feature will always be available. To the extent permitted by applicable law, Storvex is provided as available, without warranties that cannot truthfully be made about all uses or outcomes.</p></section>
      <section><h2>12. Changes to these terms</h2><p>We may update these terms to reflect service, provider, or requirement changes. We will publish the revised terms here and update the date above. Continued use after an update takes effect means the updated terms apply, subject to any notice or consent required by applicable law.</p></section>
      <section className="legal-contact"><h2>Contact us</h2><p>Questions about these terms can be sent to <a href="mailto:support@storvex.rw">support@storvex.rw</a>.</p></section>
    </LegalPage>
  );
}
