ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MARK_RECEIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADD_PAYMENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_DELETED';
