const SITE_URL = "https://www.storvex.rw";

export const industryPages = [
  {
    slug: "electronics",
    title: "Electronics Shop Management Software | Storvex",
    description: "Keep electronics stock, sales, device details, warranty records and product images clear with Storvex shop management software.",
    eyebrow: "Electronics shops",
    h1: "Keep electronics stock, sales and device details in one clear place.",
    intro: "Phones and laptops can look the same but have different details. Storvex helps your workers find the right product record without checking many boxes or old receipts.",
    accent: "blue",
    products: ["Phones", "Laptops", "TVs", "Accessories"],
    problemTitle: "Similar devices are easy to mix up.",
    problemText: "A phone may have a different model, storage, memory, colour or condition. If those details are only on a box, a worker must stop and search before helping the customer.",
    fasterTitle: "Spend less time checking device details.",
    toolsTitle: "Use your device records for stock, sales and buying.",
    dayTitle: "Help customers without checking every box.",
    daySteps: [
      ["A customer asks for a phone", "The worker opens the saved model, storage, memory, colour and condition."],
      ["The sale is recorded", "The product and sale stay together, and the stock record is updated."],
      ["The owner checks later", "The owner can see what was sold and which electronics need attention."],
    ],
    recordName: "Example phone record",
    recordNote: "Only save a serial number or IMEI when your shop uses it.",
    facts: [["Model", "Galaxy A15"], ["Storage", "128 GB"], ["IMEI or serial", "Saved when used"], ["Warranty", "Record available"]],
    faster: [["Before", "Open boxes, read labels and search old receipts."], ["With Storvex", "Open one saved product record and check the details."], ["Result", "Find the right device faster and keep the sale clear."]],
    tools: [
      ["Inventory management", "Keep device details with the stock record.", "/solutions/inventory-management"],
      ["Sales tracking", "See which electronics were sold.", "/solutions/sales-tracking"],
      ["Stock reordering", "Find electronics that may need to be bought again.", "/solutions/stock-reordering"],
    ],
    marketplaceText: "Add approved product images and publish selected electronics for customers to find on Storvex Marketplace. Customers send an order request; they do not pay the shop through Storvex.",
    ctaTitle: "Spend less time checking boxes and old receipts.",
  },
  {
    slug: "hardware",
    title: "Hardware Shop Management Software | Storvex",
    description: "Track hardware stock, sales, product sizes, selling units, suppliers and purchase orders with Storvex shop management software.",
    eyebrow: "Hardware shops",
    h1: "Know what hardware is left, what was sold and what to buy again.",
    intro: "Tools and building materials often differ by size, unit, grade or material. Save those details once so workers can use them while selling, checking stock and buying again.",
    accent: "orange",
    products: ["Tools", "Cement", "Iron sheets", "Paint", "Fittings"],
    problemTitle: "Small product differences can cause a wrong sale.",
    problemText: "Two products may look alike but have a different size, grade or selling unit. Notes on loose paper make it harder to know which one was sold and what is left.",
    fasterTitle: "Check sizes, units and low stock faster.",
    toolsTitle: "Use hardware records while selling, checking stock and buying.",
    dayTitle: "Keep product details ready during a busy sale.",
    daySteps: [
      ["A builder asks for a product", "The worker checks its saved size, unit, grade and material."],
      ["New goods arrive", "The shop records the products received from the supplier."],
      ["Stock runs low", "The owner checks the low-stock list before making the next purchase order."],
    ],
    recordName: "Example iron-sheet record",
    recordNote: "Storvex records whole stock amounts. It does not claim fractional stock control.",
    facts: [["Selling unit", "Sheet"], ["Size", "3 metres"], ["Grade", "Gauge 28"], ["Stock", "Available"]],
    faster: [["Before", "Check shelves and ask workers which size was sold."], ["With Storvex", "Use the saved unit and size while selling and checking stock."], ["Result", "Know what needs attention before the next supplier order."]],
    tools: [
      ["Inventory management", "Keep sizes, units and stock changes clear.", "/solutions/inventory-management"],
      ["Stock reordering", "Start the buying check with low-stock products.", "/solutions/stock-reordering"],
      ["Multi-branch management", "Keep hardware stock clear at each branch.", "/solutions/multi-branch-management"],
      ["Sales tracking", "See what hardware the shop sold.", "/solutions/sales-tracking"],
    ],
    marketplaceText: "Publish selected hardware products with approved details and images on Storvex Marketplace. Customers can find the product and send an order request to the shop.",
    ctaTitle: "Make hardware stock and buying checks faster.",
  },
  {
    slug: "home-and-kitchen",
    title: "Home and Kitchen Shop Management Software | Storvex",
    description: "Manage home and kitchen product details, stock, sales, suppliers and Marketplace listings with Storvex shop software.",
    eyebrow: "Home and kitchen shops",
    h1: "Find the right home product faster and keep its stock clear.",
    intro: "Cookware, appliances, furniture and bedding can differ by size, material, colour, capacity or number of pieces. Keep those details in one product record.",
    accent: "green",
    products: ["Cookware", "Appliances", "Furniture", "Bedding", "Home items"],
    problemTitle: "Products that look alike may not be the same.",
    problemText: "A customer may need a certain size, colour or capacity. When the details are not easy to find, workers reopen boxes or ask another person for help.",
    fasterTitle: "Find size, colour and set details faster.",
    toolsTitle: "Use product records while selling and checking stock.",
    dayTitle: "Answer product questions from one clear record.",
    daySteps: [
      ["A customer compares two items", "The worker checks saved material, colour, size, capacity or set pieces."],
      ["The customer buys", "The sale is recorded against the right product."],
      ["The owner checks stock", "The owner can see what is left and what may need attention."],
    ],
    recordName: "Example cookware record",
    recordNote: "Each product has its own record. Storvex does not claim automatic product variants or bundles.",
    facts: [["Material", "Stainless steel"], ["Colour", "Silver"], ["Capacity", "5 litres"], ["Pieces", "3-piece set"]],
    faster: [["Before", "Reopen a box or wait for someone who knows the product."], ["With Storvex", "Open the saved product details and image."], ["Result", "Help the customer sooner and record the right sale."]],
    tools: [
      ["Inventory management", "Keep home product details with stock.", "/solutions/inventory-management"],
      ["Sales tracking", "See which home products were sold.", "/solutions/sales-tracking"],
      ["Stock reordering", "Find products that may need to be bought again.", "/solutions/stock-reordering"],
    ],
    marketplaceText: "Use approved images and public product details to show selected home and kitchen items on Storvex Marketplace. Customers can send an order request to the shop.",
    ctaTitle: "Find home product details without reopening boxes.",
  },
  {
    slug: "lighting",
    title: "Lighting Shop Management Software | Storvex",
    description: "Keep lighting product details, stock, sales, low-stock checks and Marketplace listings clear with Storvex shop software.",
    eyebrow: "Lighting shops",
    h1: "Find the right light faster and know what is left in stock.",
    intro: "Bulbs and lights may differ by wattage, voltage, fitting or light colour. Storvex keeps these saved details with the product and stock record.",
    accent: "gold",
    products: ["Bulbs", "Ceiling lights", "Flood lights", "Solar lights", "LED strips"],
    problemTitle: "The wrong detail can lead to the wrong light being sold.",
    problemText: "A box may show the wattage, fitting, voltage and light colour, but checking each box slows the worker down. Saved product details make the first check faster.",
    fasterTitle: "Check light details without reading every box.",
    toolsTitle: "Use light records for sales, stock and buying.",
    dayTitle: "Check the label details without opening every box.",
    daySteps: [
      ["A customer asks for a light", "The worker checks wattage, voltage, fitting and light colour."],
      ["A solar light is compared", "The saved battery and power details help the worker find the right record."],
      ["The owner checks stock", "Low-stock records show which lighting products need attention."],
    ],
    recordName: "Example bulb record",
    recordNote: "Saved details help with the shop record. Storvex does not give room-lighting or electrical safety advice.",
    facts: [["Wattage", "12 W"], ["Fitting", "B22"], ["Voltage", "220–240 V"], ["Light colour", "Warm white"]],
    faster: [["Before", "Open boxes and read each label during the sale."], ["With Storvex", "Check the saved light details first."], ["Result", "Find the right record faster and keep stock clear."]],
    tools: [
      ["Inventory management", "Keep light details and stock changes together.", "/solutions/inventory-management"],
      ["Sales tracking", "See which lighting products were sold.", "/solutions/sales-tracking"],
      ["Stock reordering", "Find low-stock lights before the shelf is empty.", "/solutions/stock-reordering"],
    ],
    marketplaceText: "Publish selected lights with approved images and product details on Storvex Marketplace. Customers can find them and send an order request to the shop.",
    ctaTitle: "Help workers find the right lighting record faster.",
  },
  {
    slug: "spare-parts",
    title: "Spare Parts Shop Management Software | Storvex",
    description: "Track spare-part details, stock, sales, suppliers, low stock and Marketplace listings with Storvex shop management software.",
    eyebrow: "Spare parts shops",
    h1: "Find the right part faster and know whether it is still in stock.",
    intro: "A part can look correct but fit the wrong model, year or position. Save the part details your shop uses so workers can search one clear record first.",
    accent: "red",
    products: ["Vehicle parts", "Bearings", "Phone parts", "Computer parts", "Appliance parts"],
    problemTitle: "A part that looks right may still be wrong.",
    problemText: "Workers may check many boxes or ask several people before finding the right part. A saved part number, make, model, year and position makes the search shorter.",
    fasterTitle: "Find the right part details faster.",
    toolsTitle: "Use part records for sales, stock and branch checks.",
    dayTitle: "Start with saved part details, not a pile of boxes.",
    daySteps: [
      ["A customer asks for a part", "The worker searches the saved part number, make, model, year or position."],
      ["The worker checks the record", "Condition and useful measurements help identify the shop product."],
      ["The part is sold", "The sale and stock record show what left the shop."],
    ],
    recordName: "Example brake-part record",
    recordNote: "The shop saves the details. Storvex does not verify fitment or search a maker's parts database.",
    facts: [["Part number", "BP-1042"], ["Make", "Toyota"], ["Model", "Corolla"], ["Year", "2014–2018"]],
    faster: [["Before", "Check many boxes or ask several workers."], ["With Storvex", "Search the saved part details and stock record."], ["Result", "Find the shop record sooner and avoid guessing what is left."]],
    tools: [
      ["Inventory management", "Keep part details with stock changes.", "/solutions/inventory-management"],
      ["Sales tracking", "See which parts were sold.", "/solutions/sales-tracking"],
      ["Stock reordering", "Find parts that may need to be bought again.", "/solutions/stock-reordering"],
      ["Multi-branch management", "Check which branch holds the part.", "/solutions/multi-branch-management"],
    ],
    marketplaceText: "Publish selected parts with approved images and public details on Storvex Marketplace. Customers can find a listing and send an order request to the shop.",
    ctaTitle: "Make the first spare-part search faster.",
  },
];

export const industryPageSlugs = industryPages.map((page) => page.slug);

export function getIndustryPage(slug) {
  return industryPages.find((page) => page.slug === slug) || null;
}

export function isIndustryPageSlug(slug) {
  return industryPageSlugs.includes(String(slug || ""));
}

export function industryCanonical(slug) {
  return `${SITE_URL}/industries/${slug}`;
}
