ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_AUTO_REPLY_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_PRODUCT_REPLY_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_WELCOME_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_CATEGORY_CLARIFIER_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_UNKNOWN_ESCALATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_HUMAN_HELP_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_BUSINESS_SUPPORT_ESCALATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_BRANCH_PENDING_REPLY_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_BUY_PRODUCT_NOT_FOUND_ESCALATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_BUY_WAITING_BRANCH';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_CONVERSATION_CREATED';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_INBOUND_RECEIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_MESSAGE_SENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_MESSAGE_DELIVERED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_MESSAGE_READ';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_MESSAGE_FAILED';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_DRAFT_CREATED_FROM_BUY';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WHATSAPP_DRAFT_UPDATED_FROM_BUY';
